# Generated by Django 5.1.4 on 2024-12-25 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_setttings_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='smptserver',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smptemail',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smptpassword',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smptport',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='youtube',
        ),
        migrations.AddField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='status',
            field=models.EmailField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='setting',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
