# Generated by Django 5.1.4 on 2024-12-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_smptserver_setting_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=255)),
                ('status', models.EmailField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='message',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='note',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='update_at',
        ),
        migrations.AddField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(default='default Address', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=models.CharField(default='default contact', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.TextField(default='default description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(default='deafult email', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='keywords',
            field=models.CharField(default='default keywords', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='smptemail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='smptpassword',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='setting',
            name='smptport',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='smptserver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='title',
            field=models.CharField(default='deafult title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
