# Generated by Django 5.1.4 on 2025-01-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ру', 'Руский'), ('uz', "O'zbek")], max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('smptserver', models.CharField(blank=True, max_length=50)),
                ('smptemail', models.EmailField(blank=True, max_length=50)),
                ('smptpassword', models.CharField(blank=True, max_length=10)),
                ('smptport', models.CharField(blank=True, max_length=5)),
                ('youtube', models.URLField(blank=True, max_length=50)),
                ('instagram', models.URLField(blank=True, max_length=50)),
                ('facebook', models.URLField(blank=True, max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('aboutus', models.TextField(default='Default Address', max_length=255)),
                ('contact', models.CharField(max_length=200)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.setting')),
            ],
        ),
    ]
