# Generated by Django 5.1.4 on 2025-01-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_settinglang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Руский'), ('uz', 'Uzbek')], max_length=6),
        ),
    ]
